/*
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.users.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.users.model.LocationUpdateRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NewUserAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-29T09:49:58.273618+01:00[Europe/Rome]")
public class NewUserAllOf {
  public static final String SERIALIZED_NAME_SSO_IDENTIFIER = "ssoIdentifier";
  @SerializedName(SERIALIZED_NAME_SSO_IDENTIFIER)
  private String ssoIdentifier;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private LocationUpdateRequest location;


  public NewUserAllOf ssoIdentifier(String ssoIdentifier) {
    
    this.ssoIdentifier = ssoIdentifier;
    return this;
  }

   /**
   * Get ssoIdentifier
   * @return ssoIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSsoIdentifier() {
    return ssoIdentifier;
  }



  public void setSsoIdentifier(String ssoIdentifier) {
    this.ssoIdentifier = ssoIdentifier;
  }


  public NewUserAllOf password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPassword() {
    return password;
  }



  public void setPassword(String password) {
    this.password = password;
  }


  public NewUserAllOf location(LocationUpdateRequest location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocationUpdateRequest getLocation() {
    return location;
  }



  public void setLocation(LocationUpdateRequest location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewUserAllOf newUserAllOf = (NewUserAllOf) o;
    return Objects.equals(this.ssoIdentifier, newUserAllOf.ssoIdentifier) &&
        Objects.equals(this.password, newUserAllOf.password) &&
        Objects.equals(this.location, newUserAllOf.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ssoIdentifier, password, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewUserAllOf {\n");
    sb.append("    ssoIdentifier: ").append(toIndentedString(ssoIdentifier)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

