/*
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.users.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.users.model.UserListItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Users
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-29T09:49:58.273618+01:00[Europe/Rome]")
public class Users {
  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit;

  public static final String SERIALIZED_NAME_NEXT_PAGE_ID = "nextPageId";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE_ID)
  private String nextPageId;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private List<UserListItem> content = null;


  public Users limit(Integer limit) {
    
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getLimit() {
    return limit;
  }



  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  public Users nextPageId(String nextPageId) {
    
    this.nextPageId = nextPageId;
    return this;
  }

   /**
   * Get nextPageId
   * @return nextPageId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNextPageId() {
    return nextPageId;
  }



  public void setNextPageId(String nextPageId) {
    this.nextPageId = nextPageId;
  }


  public Users content(List<UserListItem> content) {
    
    this.content = content;
    return this;
  }

  public Users addContentItem(UserListItem contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<UserListItem>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<UserListItem> getContent() {
    return content;
  }



  public void setContent(List<UserListItem> content) {
    this.content = content;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Users users = (Users) o;
    return Objects.equals(this.limit, users.limit) &&
        Objects.equals(this.nextPageId, users.nextPageId) &&
        Objects.equals(this.content, users.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limit, nextPageId, content);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Users {\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    nextPageId: ").append(toIndentedString(nextPageId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

