/*
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.users.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.users.model.SystemRole;
import com.smartrecruiters.api.users.model.User;
import com.smartrecruiters.api.users.model.UserLanguage;
import com.smartrecruiters.api.users.model.UserListItemAllOf;
import com.smartrecruiters.api.users.model.UserListItemAllOfAccessGroups;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * UserListItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-29T09:49:58.273618+01:00[Europe/Rome]")
public class UserListItem {
  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_SYSTEM_ROLE = "systemRole";
  @SerializedName(SERIALIZED_NAME_SYSTEM_ROLE)
  private SystemRole systemRole;

  public static final String SERIALIZED_NAME_EXTERNAL_DATA = "externalData";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_DATA)
  private String externalData;

  public static final String SERIALIZED_NAME_SSO_IDENTIFIER = "ssoIdentifier";
  @SerializedName(SERIALIZED_NAME_SSO_IDENTIFIER)
  private String ssoIdentifier;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private UserLanguage language;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_UPDATED_ON = "updatedOn";
  @SerializedName(SERIALIZED_NAME_UPDATED_ON)
  private OffsetDateTime updatedOn;

  public static final String SERIALIZED_NAME_ACCESS_GROUPS = "accessGroups";
  @SerializedName(SERIALIZED_NAME_ACCESS_GROUPS)
  private List<UserListItemAllOfAccessGroups> accessGroups = null;


  public UserListItem email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(required = true, value = "")

  public String getEmail() {
    return email;
  }



  public void setEmail(String email) {
    this.email = email;
  }


  public UserListItem firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getFirstName() {
    return firstName;
  }



  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public UserListItem lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLastName() {
    return lastName;
  }



  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public UserListItem systemRole(SystemRole systemRole) {
    
    this.systemRole = systemRole;
    return this;
  }

   /**
   * Get systemRole
   * @return systemRole
  **/
  @ApiModelProperty(required = true, value = "")

  public SystemRole getSystemRole() {
    return systemRole;
  }



  public void setSystemRole(SystemRole systemRole) {
    this.systemRole = systemRole;
  }


  public UserListItem externalData(String externalData) {
    
    this.externalData = externalData;
    return this;
  }

   /**
   * Get externalData
   * @return externalData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExternalData() {
    return externalData;
  }



  public void setExternalData(String externalData) {
    this.externalData = externalData;
  }


  public UserListItem ssoIdentifier(String ssoIdentifier) {
    
    this.ssoIdentifier = ssoIdentifier;
    return this;
  }

   /**
   * Get ssoIdentifier
   * @return ssoIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSsoIdentifier() {
    return ssoIdentifier;
  }



  public void setSsoIdentifier(String ssoIdentifier) {
    this.ssoIdentifier = ssoIdentifier;
  }


  public UserListItem language(UserLanguage language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(required = true, value = "")

  public UserLanguage getLanguage() {
    return language;
  }



  public void setLanguage(UserLanguage language) {
    this.language = language;
  }


  public UserListItem id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public UserListItem active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getActive() {
    return active;
  }



  public void setActive(Boolean active) {
    this.active = active;
  }


  public UserListItem updatedOn(OffsetDateTime updatedOn) {
    
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * Get updatedOn
   * @return updatedOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }



  public void setUpdatedOn(OffsetDateTime updatedOn) {
    this.updatedOn = updatedOn;
  }


  public UserListItem accessGroups(List<UserListItemAllOfAccessGroups> accessGroups) {
    
    this.accessGroups = accessGroups;
    return this;
  }

  public UserListItem addAccessGroupsItem(UserListItemAllOfAccessGroups accessGroupsItem) {
    if (this.accessGroups == null) {
      this.accessGroups = new ArrayList<UserListItemAllOfAccessGroups>();
    }
    this.accessGroups.add(accessGroupsItem);
    return this;
  }

   /**
   * Get accessGroups
   * @return accessGroups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<UserListItemAllOfAccessGroups> getAccessGroups() {
    return accessGroups;
  }



  public void setAccessGroups(List<UserListItemAllOfAccessGroups> accessGroups) {
    this.accessGroups = accessGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserListItem userListItem = (UserListItem) o;
    return Objects.equals(this.email, userListItem.email) &&
        Objects.equals(this.firstName, userListItem.firstName) &&
        Objects.equals(this.lastName, userListItem.lastName) &&
        Objects.equals(this.systemRole, userListItem.systemRole) &&
        Objects.equals(this.externalData, userListItem.externalData) &&
        Objects.equals(this.ssoIdentifier, userListItem.ssoIdentifier) &&
        Objects.equals(this.language, userListItem.language) &&
        Objects.equals(this.id, userListItem.id) &&
        Objects.equals(this.active, userListItem.active) &&
        Objects.equals(this.updatedOn, userListItem.updatedOn) &&
        Objects.equals(this.accessGroups, userListItem.accessGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, firstName, lastName, systemRole, externalData, ssoIdentifier, language, id, active, updatedOn, accessGroups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserListItem {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    systemRole: ").append(toIndentedString(systemRole)).append("\n");
    sb.append("    externalData: ").append(toIndentedString(externalData)).append("\n");
    sb.append("    ssoIdentifier: ").append(toIndentedString(ssoIdentifier)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    accessGroups: ").append(toIndentedString(accessGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

