/*
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.users.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Language code, can be two-letter for the standard variant or with additional two letters after a hyphen to identify a specific locale
 */
@JsonAdapter(UserLanguageCode.Adapter.class)
public enum UserLanguageCode {
  
  AF("af"),
  
  AR("ar"),
  
  BG("bg"),
  
  CS("cs"),
  
  DA("da"),
  
  DE("de"),
  
  EL("el"),
  
  EN("en"),
  
  ES("es"),
  
  ES_MX("es-MX"),
  
  FI("fi"),
  
  FR("fr"),
  
  FR_CA("fr-CA"),
  
  HE("he"),
  
  HR("hr"),
  
  HU("hu"),
  
  ID("id"),
  
  IT("it"),
  
  JA("ja"),
  
  KO("ko"),
  
  LT("lt"),
  
  NL("nl"),
  
  NO("no"),
  
  PL("pl"),
  
  PT("pt"),
  
  PT_BR("pt-BR"),
  
  RO("ro"),
  
  RU("ru"),
  
  SK("sk"),
  
  SL("sl"),
  
  SR("sr"),
  
  SV("sv"),
  
  TH("th"),
  
  TR("tr"),
  
  UK("uk"),
  
  VI("vi"),
  
  ZH_CN("zh-CN"),
  
  ZH_TW("zh-TW");

  private String value;

  UserLanguageCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UserLanguageCode fromValue(String value) {
    for (UserLanguageCode b : UserLanguageCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<UserLanguageCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final UserLanguageCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public UserLanguageCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return UserLanguageCode.fromValue(value);
    }
  }
}

